"""
Directely add/remove routes to the table for windows without BAT.
"""
import os, json
from chnroutes import fetch_ip_data
from multiprocessing import Pool, cpu_count
#==============================================================================
def LoadIpFromJson(fn=r'./routes_cn.json'):
    """ Load ip data from json format file. 
        Json file generated by bestroutetb:
          "bestroutetb --route.net=cn -p json -o routes_cn.json"
    """
    with open(fn,'r') as fid:
        dicLst = json.load(fid)

    return [(d['prefix'], d['mask'], None) 
                for d in dicLst if d['gateway']=='net']


def AddRouteMP(dataLst, gateway='192.168.11.1', metric=5, pool=None):
    Map = map if pool is None else pool.map
    addCmdLst = [ 'route ADD %s MASK %s %s METRIC %d'%(ip, mask, gateway, metric) 
                    for (ip, mask, mask2) in dataLst ]

    os.system('ipconfig /flushdns') # clear dns 1st
    Map(os.system, addCmdLst)


def DelRouteMP(dataLst, pool=None):
    Map = map if pool is None else pool.map

    delCmdLst = [ 'route DELETE %s'%ip for (ip, mask, mask2) in dataLst ]

    Map(os.system, delCmdLst)


#==============================================================================
if __name__ == '__main__':
    GATEWAY = '192.168.11.1'
    # dataLst = fetch_ip_data(r'./delegated-apnic-latest.txt')
    dataLst = LoadIpFromJson(r'./routes_cn.json')
    print('IP record number: %i'%len(dataLst))

    p = Pool(processes=cpu_count(), maxtasksperchild=1000)
    # p = None
    done = False
    while not done:
        arg=raw_input('[A]dd or [D]elele routes (or [E]xit):\n-->>')
        if arg=='A' or arg=='a':
            AddRouteMP(dataLst, gateway=GATEWAY, metric=5, pool=p)
            done = True
        elif arg=='D' or arg=='d':
            DelRouteMP(dataLst, pool=p)
            done = True
        elif arg=='E' or arg=='e':
            done = True
        else:
            print('InputError.\n')

    p.close(); p.join()